language: node_js
node_js:
  - "10.8.0"
cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn install
script:
  - yarn test

deploy:
  provider: heroku
  api_key: ...
  app: naked-budget-core
